[package]
name = "bftd"
version = "0.1.0"
edition = "2021"

[dependencies]
bftd-core = { path = "../bftd-core" }
clap = { version = "4.5.7", features = ["derive"] }
anyhow = "1.0.86"
rand = "0.8.5"
toml = "0.8.14"
