{
 "title": "Bftd",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "TPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(load_gen_sent_transactions[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Commit latency(ms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(syncer_own_block_commit_age_ms_sum[1m]) / rate(syncer_own_block_commit_age_ms_count[1m]) ",
     "legendFormat": "{{validator}}"
    }
   ]
  },
  {
   "title": "CPU util(%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "100 - avg by (validator) (rate(node_cpu_seconds_total{mode=\"idle\"}[1m])) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "IO util (%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "rate(node_disk_io_time_seconds_total{device=\"sda\"}[1m])*100",
     "legendFormat": "{{validator}}"
    }
   ]
  },
  {
   "title": "Disk written (Mb/s)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "rate(node_disk_written_bytes_total{device=\"sda\"}[1m]) / 1024 / 1024",
     "legendFormat": "{{validator}}"
    }
   ]
  },
  {
   "title": "Disk read(Mb/s)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "rate(node_disk_read_bytes_total{device=\"sda\"}[1m]) / 1024 / 1024",
     "legendFormat": "{{validator}}"
    }
   ]
  },
  {
   "title": "Network recieve(Mbp/s)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total[1m]) / 1024 / 1024 * 8",
     "legendFormat": "{{validator}}"
    }
   ]
  },
  {
   "title": "Network send (Mbp/s)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "rate(node_network_transmit_bytes_total[1m]) / 1024 / 1024 * 8",
     "legendFormat": "{{validator}}"
    }
   ]
  },
  {
   "title": "Rounds per second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "rate(core_last_proposed_round[1m])",
     "legendFormat": "{{validator}}"
    }
   ]
  },
  {
   "title": "Syncer main loop util (ms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "targets": [
    {
     "expr": "rate(syncer_main_loop_util_ns[1m]) / 1000 / 1000",
     "legendFormat": "{{validator}}"
    }
   ]
  },
  {
   "title": "Disk available (Gb)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes{device=\"/dev/sda\"} / 1024 / 1024 / 1024",
     "legendFormat": "{{validator}}"
    }
   ]
  },
  {
   "title": "Available memory (Gb)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "targets": [
    {
     "expr": "node_memory_MemAvailable_bytes / 1024 / 1024/ 1024",
     "legendFormat": "{{validator}}"
    }
   ]
  }
 ]
}