[package]
name = "bftd-types"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.203", features = ["derive"] }
serde_with = { version = "3.9.0" , features = ["base64"]}
serde_json = "1.0.128"
bytes = { version = "1.7.2", features = ["serde"] }
